### ISSUE TITLE
Remove the maximum length on passwords

### ISSUE THREAD

**Issue by Throne3d** [Marri/glowfic#136]
It's bad practice to put a max length on it, I'm pretty sure. I don't see why there should be a max limit.

**Comment by youve** [comment]
It should have a max length so somebody doesn't submit the entire works of shakespeare as their password but a reasonable limit that would probably inconvenience nobody would be 127 or 255 characters. (my own longest passphrases are in the 80-100 character range).

A minimum password length of 10 characters will rule out most of the ones on the list of "100k most commonly used passwords"; which is useful for preventing, among other things, people's accounts being taken over by spambots.

**Comment by Throne3d** [comment]
I think the minimum of 6 is reasonable, at least for now (or maybe a minimum of 8 – most sites allow passwords of length 8).

What's the problem with someone submitting the entire works of shakespeare, except insofar as that would take a long time to transfer? If there's a problem with them submitting a large amount of data here, it would apply everywhere and we should implement maximums in other locations – though I'm not sure how to actually enforce it in the HTTP requests, only that it could be enforced in the form itself. If the problem is just a large amount of data, there's no more issue with it being allowed here than anywhere else.

**Comment by youve** [comment]
Well they'd probably not be able to login because it'd timeout but it's more of a sanity check type thing. after a certain length it's more likely that the user accidentally hit ctrl-v in the password form than anything, and they didn't want to set their new password to be "pass[lots and lots of text here]word"

I was at first thinking that the password length would affect the field type in the database and you'd have to set it like varchar(8) or something but of course passwords should be stored encrypted and salted anyway so it won't affect that at all; password length shouldn't correlate to the length of what's actually stored in the database anyway.

forms can be checked with javascript on the client side that the basics are okay and then when the form is submitted also checked on the server side.

**Comment by Throne3d** [comment]
So the maximum should be removed from the backend logic and we should maybe add a sanity check for passwords over the length of e.g. 100 characters.

When changing a password, you have to fill in the 'new password' box as well as the 'confirm new password' box, so if they did paste incorrectly it'd be likely they *copied* incorrectly and then intentionally pasted it twice, which is a different matter and they should then reset their password using the email system or by contacting an admin.

It makes some sense for there to be a check for passwords over the length of 100 characters, but we shouldn't prohibit them. If someone wants a password that's 1024 characters long, it shouldn't (with modern technology) take long to transmit nor to process, I don't think, and so we should allow it.
