### ISSUE TITLE
Social embed data

### ISSUE THREAD

**Issue by Marri** [Marri/glowfic#200]
When [linking to a post on Reddit](https://www.reddit.com/r/glowfic/comments/6521wv/silmaril/), it picks a random image as a thumbnail, which is often "random face icon". This is suboptimal and should be fixed if possible.

**Comment by Marri** [comment]
http://stackoverflow.com/questions/10864208/how-do-i-get-facebook-to-show-my-sites-logo-when-i-paste-the-link-in-a-post-sta

**Comment by Throne3d** [comment]
Relatedly: getting Discord to show a proper embed when constellation links are used.

I would prefer to have the description text be relatively short, because large embeds on discord are annoying, and it would be useful to have the embed so we know what thread a link points to etc. It looks like this is `og`. GitHub has quite a lot of `og` `meta`s in its `head`, so that seems useful as an example of what we want to aim for.
